// AUTO-GENERATED by scripts/gen-scenes.ts — do not edit by hand.
// Run `pnpm gen` in this package to regenerate from scripts/TESTS.md.
/* eslint-disable */
import type { Scene } from 'motion-script';

import s_rect_basic from './rect-basic';
import s_rect_corner_radius from './rect-corner-radius';
import s_rect_corner_radius_per_corner from './rect-corner-radius-per-corner';
import s_rect_corner_style_angled from './rect-corner-style-angled';
import s_ellipse_circle from './ellipse-circle';
import s_ellipse_arc from './ellipse-arc';
import s_ellipse_pie from './ellipse-pie';
import s_ellipse_ratio from './ellipse-ratio';
import s_polygon_triangle from './polygon-triangle';
import s_polygon_pentagon from './polygon-pentagon';
import s_polygon_hexagon from './polygon-hexagon';
import s_polygon_corner_radius from './polygon-corner-radius';
import s_polygon_corner_angled from './polygon-corner-angled';
import s_polygram_star_5 from './polygram-star-5';
import s_polygram_star_6 from './polygram-star-6';
import s_polygram_star_ratio from './polygram-star-ratio';
import s_polygram_rounded from './polygram-rounded';
import s_path_svg_string from './path-svg-string';
import s_path_morph from './path-morph';
import s_line_open from './line-open';
import s_line_closed from './line-closed';
import s_line_rounded from './line-rounded';
import s_rect_layout_row from './rect-layout-row';
import s_rect_layout_column from './rect-layout-column';
import s_rect_layout_stack from './rect-layout-stack';
import s_rect_layout_gap from './rect-layout-gap';
import s_rect_layout_padding from './rect-layout-padding';
import s_rect_layout_padding_per_side from './rect-layout-padding-per-side';
import s_rect_size_fill from './rect-size-fill';
import s_rect_size_hug from './rect-size-hug';
import s_rect_size_max_constraints from './rect-size-max-constraints';
import s_flex_align from './flex-align';
import s_flex_main_flex from './flex-main-flex';
import s_grid_basic from './grid-basic';
import s_grid_colspan from './grid-colspan';
import s_text_basic from './text-basic';
import s_text_multiline_wrap from './text-multiline-wrap';
import s_text_align_variants from './text-align-variants';
import s_text_font_weight from './text-font-weight';
import s_text_letter_spacing from './text-letter-spacing';
import s_text_line_height from './text-line-height';
import s_text_autofit from './text-autofit';
import s_text_on_path from './text-on-path';
import s_text_fill_gradient from './text-fill-gradient';
import s_richtext_basic from './richtext-basic';
import s_richtext_inline_stroke from './richtext-inline-stroke';
import s_number_node_integer from './number-node-integer';
import s_number_node_currency from './number-node-currency';
import s_number_node_percent from './number-node-percent';
import s_image_fit_fill from './image-fit-fill';
import s_image_fit_fit from './image-fit-fit';
import s_image_fit_tile from './image-fit-tile';
import s_image_fit_stretch from './image-fit-stretch';
import s_image_crop from './image-crop';
import s_image_zoom_anchor from './image-zoom-anchor';
import s_video_playback from './video-playback';
import s_video_speed from './video-speed';
import s_video_loop from './video-loop';
import s_camera_zoom from './camera-zoom';
import s_camera_pan from './camera-pan';
import s_camera_heading from './camera-heading';
import s_camera_combined from './camera-combined';
import s_mask_alpha from './mask-alpha';
import s_mask_vector from './mask-vector';
import s_mask_luminance from './mask-luminance';
import s_mask_invert from './mask-invert';
import s_mask_apply_fill from './mask-apply-fill';
import s_mask_apply_stroke from './mask-apply-stroke';
import s_boolean_toggle from './boolean-toggle';
import s_provider_theme from './provider-theme';
import s_default_text_style from './default-text-style';
import s_line_grid_basic from './line-grid-basic';
import s_line_grid_subdivisions from './line-grid-subdivisions';
import s_grid_pattern_basic from './grid-pattern-basic';
import s_grid_pattern_subdivisions from './grid-pattern-subdivisions';
import s_code_basic from './code-basic';
import s_code_theme_github_dark from './code-theme-github-dark';
import s_code_theme_github_light from './code-theme-github-light';
import s_code_theme_vscode_dark from './code-theme-vscode-dark';
import s_code_theme_vscode_light from './code-theme-vscode-light';
import s_code_line_numbers from './code-line-numbers';
import s_code_padding from './code-padding';
import s_code_append from './code-append';
import s_code_prepend from './code-prepend';
import s_code_insert from './code-insert';
import s_code_remove from './code-remove';
import s_code_replace from './code-replace';
import s_code_highlight from './code-highlight';
import s_code_highlight_reset from './code-highlight-reset';
import s_latex_basic from './latex-basic';
import s_latex_complex from './latex-complex';
import s_latex_morph from './latex-morph';
import s_latex_fill_gradient from './latex-fill-gradient';
import s_latex_stroke from './latex-stroke';
import s_fill_solid from './fill-solid';
import s_fill_linear_gradient from './fill-linear-gradient';
import s_fill_radial_gradient from './fill-radial-gradient';
import s_fill_conic_gradient from './fill-conic-gradient';
import s_fill_image from './fill-image';
import s_fill_video from './fill-video';
import s_fill_noise from './fill-noise';
import s_fill_shader_custom from './fill-shader-custom';
import s_fill_stripe from './fill-stripe';
import s_view3d_basic from './view3d-basic';
import s_view3d_fill_shape from './view3d-fill-shape';
import s_view3d_tex_surface from './view3d-tex-surface';
import s_view3d_translucent from './view3d-translucent';
import s_fill_space_local from './fill-space-local';
import s_fill_space_parent from './fill-space-parent';
import s_fill_space_global from './fill-space-global';
import s_fill_layered from './fill-layered';
import s_overlay_basic from './overlay-basic';
import s_overlay_video from './overlay-video';
import s_stroke_align_inside from './stroke-align-inside';
import s_stroke_align_center from './stroke-align-center';
import s_stroke_align_outside from './stroke-align-outside';
import s_stroke_cap_butt from './stroke-cap-butt';
import s_stroke_cap_round from './stroke-cap-round';
import s_stroke_cap_square from './stroke-cap-square';
import s_stroke_join_miter from './stroke-join-miter';
import s_stroke_join_round from './stroke-join-round';
import s_stroke_join_bevel from './stroke-join-bevel';
import s_stroke_dash_uniform from './stroke-dash-uniform';
import s_stroke_dash_pair from './stroke-dash-pair';
import s_stroke_dash_animated from './stroke-dash-animated';
import s_stroke_gradient_fill from './stroke-gradient-fill';
import s_stroke_layered from './stroke-layered';
import s_stroke_miter_limit from './stroke-miter-limit';
import s_shadow_drop_basic from './shadow-drop-basic';
import s_shadow_drop_offset from './shadow-drop-offset';
import s_shadow_drop_blur from './shadow-drop-blur';
import s_shadow_inner from './shadow-inner';
import s_shadow_spread_positive from './shadow-spread-positive';
import s_shadow_spread_negative from './shadow-spread-negative';
import s_shadow_fill_gradient from './shadow-fill-gradient';
import s_shadow_layered from './shadow-layered';
import s_effect_blur from './effect-blur';
import s_effect_blur_backdrop from './effect-blur-backdrop';
import s_effect_directional_blur from './effect-directional-blur';
import s_effect_directional_blur_backdrop from './effect-directional-blur-backdrop';
import s_effect_grayscale from './effect-grayscale';
import s_effect_grayscale_backdrop from './effect-grayscale-backdrop';
import s_effect_pixelate from './effect-pixelate';
import s_effect_pixelate_sharp from './effect-pixelate-sharp';
import s_effect_pixelate_backdrop from './effect-pixelate-backdrop';
import s_effect_bulge_barrel from './effect-bulge-barrel';
import s_effect_bulge_pincushion from './effect-bulge-pincushion';
import s_effect_magnify from './effect-magnify';
import s_effect_bloom from './effect-bloom';
import s_effect_vintage from './effect-vintage';
import s_effect_chromatic_aberration from './effect-chromatic-aberration';
import s_effect_invert from './effect-invert';
import s_effect_scatter_horizontal from './effect-scatter-horizontal';
import s_effect_scatter_vertical from './effect-scatter-vertical';
import s_effect_scatter_both from './effect-scatter-both';
import s_effect_posterize from './effect-posterize';
import s_effect_outline from './effect-outline';
import s_effect_outline_inside from './effect-outline-inside';
import s_effect_vignette from './effect-vignette';
import s_effect_grain from './effect-grain';
import s_effect_sharpen from './effect-sharpen';
import s_effect_edges from './effect-edges';
import s_effect_threshold from './effect-threshold';
import s_effect_radial_blur from './effect-radial-blur';
import s_effect_radial_blur_spin from './effect-radial-blur-spin';
import s_effect_halftone from './effect-halftone';
import s_effect_dither from './effect-dither';
import s_effect_duotone from './effect-duotone';
import s_effect_curves from './effect-curves';
import s_effect_color_adjustment from './effect-color-adjustment';
import s_effect_rgb_shift from './effect-rgb-shift';
import s_effect_scanlines from './effect-scanlines';
import s_effect_block_displace from './effect-block-displace';
import s_effect_bit_crush from './effect-bit-crush';
import s_effect_streak from './effect-streak';
import s_effect_god_rays from './effect-god-rays';
import s_effect_oil_paint from './effect-oil-paint';
import s_effect_texture from './effect-texture';
import s_effect_ascii from './effect-ascii';
import s_effect_chain_order from './effect-chain-order';
import s_effect_sksl_custom from './effect-sksl-custom';
import s_effect_sksl_backdrop from './effect-sksl-backdrop';
import s_filter_exposure from './filter-exposure';
import s_filter_blur_image from './filter-blur-image';
import s_filter_grayscale_image from './filter-grayscale-image';
import s_filter_alpha_image from './filter-alpha-image';
import s_filter_color_matrix from './filter-color-matrix';
import s_filter_curves from './filter-curves';
import s_filter_curves_per_channel from './filter-curves-per-channel';
import s_filter_color_adjustment from './filter-color-adjustment';
import s_filter_video_exposure from './filter-video-exposure';
import s_filter_video_grayscale from './filter-video-grayscale';
import s_filter_video_color_adjustment from './filter-video-color-adjustment';
import s_filter_video_posterize_time from './filter-video-posterize-time';
import s_filter_video_echo from './filter-video-echo';
import s_blend_node_multiply from './blend-node-multiply';
import s_blend_node_screen from './blend-node-screen';
import s_blend_node_overlay from './blend-node-overlay';
import s_blend_node_darken from './blend-node-darken';
import s_blend_node_lighten from './blend-node-lighten';
import s_blend_node_color_dodge from './blend-node-color-dodge';
import s_blend_node_color_burn from './blend-node-color-burn';
import s_blend_node_hard_light from './blend-node-hard-light';
import s_blend_node_soft_light from './blend-node-soft-light';
import s_blend_node_difference from './blend-node-difference';
import s_blend_node_exclusion from './blend-node-exclusion';
import s_blend_node_hue from './blend-node-hue';
import s_blend_node_saturation from './blend-node-saturation';
import s_blend_node_color from './blend-node-color';
import s_blend_node_luminosity from './blend-node-luminosity';
import s_blend_node_pass_through from './blend-node-pass-through';
import s_blend_fill_multiply from './blend-fill-multiply';
import s_blend_fill_screen from './blend-fill-screen';
import s_blend_fill_overlay from './blend-fill-overlay';
import s_blend_fill_difference from './blend-fill-difference';
import s_blend_fill_color_dodge from './blend-fill-color-dodge';
import s_blend_fill_luminosity from './blend-fill-luminosity';
import s_blend_fill_layered_stack from './blend-fill-layered-stack';
import s_blend_stroke_screen from './blend-stroke-screen';
import s_blend_stroke_multiply from './blend-stroke-multiply';
import s_blend_stroke_difference from './blend-stroke-difference';
import s_blend_shadow_screen from './blend-shadow-screen';
import s_blend_shadow_multiply from './blend-shadow-multiply';
import s_blend_shadow_color_dodge from './blend-shadow-color-dodge';
import s_transform_position from './transform-position';
import s_transform_rotation from './transform-rotation';
import s_transform_scale_uniform from './transform-scale-uniform';
import s_transform_scale_xy from './transform-scale-xy';
import s_transform_opacity from './transform-opacity';
import s_transform_pivot_center from './transform-pivot-center';
import s_transform_pivot_corner from './transform-pivot-corner';
import s_transform_pivot_custom from './transform-pivot-custom';
import s_transform_combined from './transform-combined';
import s_ease_sine from './ease-sine';
import s_ease_quad from './ease-quad';
import s_ease_cubic from './ease-cubic';
import s_ease_quart from './ease-quart';
import s_ease_quint from './ease-quint';
import s_ease_expo from './ease-expo';
import s_ease_circ from './ease-circ';
import s_ease_back from './ease-back';
import s_ease_elastic from './ease-elastic';
import s_ease_bounce from './ease-bounce';
import s_cardinal_node_topleft from './cardinal-node-topleft';
import s_cardinal_node_topcenter from './cardinal-node-topcenter';
import s_cardinal_node_topright from './cardinal-node-topright';
import s_cardinal_node_leftcenter from './cardinal-node-leftcenter';
import s_cardinal_node_center from './cardinal-node-center';
import s_cardinal_node_rightcenter from './cardinal-node-rightcenter';
import s_cardinal_node_bottomleft from './cardinal-node-bottomleft';
import s_cardinal_node_bottomcenter from './cardinal-node-bottomcenter';
import s_cardinal_node_bottomright from './cardinal-node-bottomright';
import s_cardinal_graphics_points from './cardinal-graphics-points';
import s_cardinal_graphics_rect from './cardinal-graphics-rect';
import s_cardinal_graphics_text from './cardinal-graphics-text';
import s_cardinal_graphics_ellipse from './cardinal-graphics-ellipse';
import s_cardinal_graphics_polygon from './cardinal-graphics-polygon';
import s_cardinal_graphics_polygram from './cardinal-graphics-polygram';
import s_shape_start_end_rect from './shape-start-end-rect';
import s_shape_start_end_ellipse from './shape-start-end-ellipse';
import s_shape_start_end_polygon from './shape-start-end-polygon';
import s_shape_start_end_line from './shape-start-end-line';
import s_morph_triangle_to_star from './morph-triangle-to-star';
import s_morph_circle_to_rect from './morph-circle-to-rect';
import s_morph_complex_shapes from './morph-complex-shapes';
import s_opacity_node from './opacity-node';
import s_opacity_fill from './opacity-fill';
import s_opacity_stroke from './opacity-stroke';
import s_opacity_passthrough_vs_normal from './opacity-passthrough-vs-normal';
import s_preset_vhs from './preset-vhs';
import s_preset_comic from './preset-comic';

// Named here rather than by a build transform: the ?scene suffix that used to
// stamp a name is gone, and the harness addresses scenes by it.
s_rect_basic.name = "RectBasic";
s_rect_corner_radius.name = "RectCornerRadius";
s_rect_corner_radius_per_corner.name = "RectCornerRadiusPerCorner";
s_rect_corner_style_angled.name = "RectCornerStyleAngled";
s_ellipse_circle.name = "EllipseCircle";
s_ellipse_arc.name = "EllipseArc";
s_ellipse_pie.name = "EllipsePie";
s_ellipse_ratio.name = "EllipseRatio";
s_polygon_triangle.name = "PolygonTriangle";
s_polygon_pentagon.name = "PolygonPentagon";
s_polygon_hexagon.name = "PolygonHexagon";
s_polygon_corner_radius.name = "PolygonCornerRadius";
s_polygon_corner_angled.name = "PolygonCornerAngled";
s_polygram_star_5.name = "PolygramStar5";
s_polygram_star_6.name = "PolygramStar6";
s_polygram_star_ratio.name = "PolygramStarRatio";
s_polygram_rounded.name = "PolygramRounded";
s_path_svg_string.name = "PathSvgString";
s_path_morph.name = "PathMorph";
s_line_open.name = "LineOpen";
s_line_closed.name = "LineClosed";
s_line_rounded.name = "LineRounded";
s_rect_layout_row.name = "RectLayoutRow";
s_rect_layout_column.name = "RectLayoutColumn";
s_rect_layout_stack.name = "RectLayoutStack";
s_rect_layout_gap.name = "RectLayoutGap";
s_rect_layout_padding.name = "RectLayoutPadding";
s_rect_layout_padding_per_side.name = "RectLayoutPaddingPerSide";
s_rect_size_fill.name = "RectSizeFill";
s_rect_size_hug.name = "RectSizeHug";
s_rect_size_max_constraints.name = "RectSizeMaxConstraints";
s_flex_align.name = "FlexAlign";
s_flex_main_flex.name = "FlexMainFlex";
s_grid_basic.name = "GridBasic";
s_grid_colspan.name = "GridColspan";
s_text_basic.name = "TextBasic";
s_text_multiline_wrap.name = "TextMultilineWrap";
s_text_align_variants.name = "TextAlignVariants";
s_text_font_weight.name = "TextFontWeight";
s_text_letter_spacing.name = "TextLetterSpacing";
s_text_line_height.name = "TextLineHeight";
s_text_autofit.name = "TextAutofit";
s_text_on_path.name = "TextOnPath";
s_text_fill_gradient.name = "TextFillGradient";
s_richtext_basic.name = "RichtextBasic";
s_richtext_inline_stroke.name = "RichtextInlineStroke";
s_number_node_integer.name = "NumberNodeInteger";
s_number_node_currency.name = "NumberNodeCurrency";
s_number_node_percent.name = "NumberNodePercent";
s_image_fit_fill.name = "ImageFitFill";
s_image_fit_fit.name = "ImageFitFit";
s_image_fit_tile.name = "ImageFitTile";
s_image_fit_stretch.name = "ImageFitStretch";
s_image_crop.name = "ImageCrop";
s_image_zoom_anchor.name = "ImageZoomAnchor";
s_video_playback.name = "VideoPlayback";
s_video_speed.name = "VideoSpeed";
s_video_loop.name = "VideoLoop";
s_camera_zoom.name = "CameraZoom";
s_camera_pan.name = "CameraPan";
s_camera_heading.name = "CameraHeading";
s_camera_combined.name = "CameraCombined";
s_mask_alpha.name = "MaskAlpha";
s_mask_vector.name = "MaskVector";
s_mask_luminance.name = "MaskLuminance";
s_mask_invert.name = "MaskInvert";
s_mask_apply_fill.name = "MaskApplyFill";
s_mask_apply_stroke.name = "MaskApplyStroke";
s_boolean_toggle.name = "BooleanToggle";
s_provider_theme.name = "ProviderTheme";
s_default_text_style.name = "DefaultTextStyle";
s_line_grid_basic.name = "LineGridBasic";
s_line_grid_subdivisions.name = "LineGridSubdivisions";
s_grid_pattern_basic.name = "GridPatternBasic";
s_grid_pattern_subdivisions.name = "GridPatternSubdivisions";
s_code_basic.name = "CodeBasic";
s_code_theme_github_dark.name = "CodeThemeGithubDark";
s_code_theme_github_light.name = "CodeThemeGithubLight";
s_code_theme_vscode_dark.name = "CodeThemeVscodeDark";
s_code_theme_vscode_light.name = "CodeThemeVscodeLight";
s_code_line_numbers.name = "CodeLineNumbers";
s_code_padding.name = "CodePadding";
s_code_append.name = "CodeAppend";
s_code_prepend.name = "CodePrepend";
s_code_insert.name = "CodeInsert";
s_code_remove.name = "CodeRemove";
s_code_replace.name = "CodeReplace";
s_code_highlight.name = "CodeHighlight";
s_code_highlight_reset.name = "CodeHighlightReset";
s_latex_basic.name = "LatexBasic";
s_latex_complex.name = "LatexComplex";
s_latex_morph.name = "LatexMorph";
s_latex_fill_gradient.name = "LatexFillGradient";
s_latex_stroke.name = "LatexStroke";
s_fill_solid.name = "FillSolid";
s_fill_linear_gradient.name = "FillLinearGradient";
s_fill_radial_gradient.name = "FillRadialGradient";
s_fill_conic_gradient.name = "FillConicGradient";
s_fill_image.name = "FillImage";
s_fill_video.name = "FillVideo";
s_fill_noise.name = "FillNoise";
s_fill_shader_custom.name = "FillShaderCustom";
s_fill_stripe.name = "FillStripe";
s_fill_space_local.name = "FillSpaceLocal";
s_fill_space_parent.name = "FillSpaceParent";
s_fill_space_global.name = "FillSpaceGlobal";
s_fill_layered.name = "FillLayered";
s_overlay_basic.name = "OverlayBasic";
s_overlay_video.name = "OverlayVideo";
s_stroke_align_inside.name = "StrokeAlignInside";
s_stroke_align_center.name = "StrokeAlignCenter";
s_stroke_align_outside.name = "StrokeAlignOutside";
s_stroke_cap_butt.name = "StrokeCapButt";
s_stroke_cap_round.name = "StrokeCapRound";
s_stroke_cap_square.name = "StrokeCapSquare";
s_stroke_join_miter.name = "StrokeJoinMiter";
s_stroke_join_round.name = "StrokeJoinRound";
s_stroke_join_bevel.name = "StrokeJoinBevel";
s_stroke_dash_uniform.name = "StrokeDashUniform";
s_stroke_dash_pair.name = "StrokeDashPair";
s_stroke_dash_animated.name = "StrokeDashAnimated";
s_stroke_gradient_fill.name = "StrokeGradientFill";
s_stroke_layered.name = "StrokeLayered";
s_stroke_miter_limit.name = "StrokeMiterLimit";
s_shadow_drop_basic.name = "ShadowDropBasic";
s_shadow_drop_offset.name = "ShadowDropOffset";
s_shadow_drop_blur.name = "ShadowDropBlur";
s_shadow_inner.name = "ShadowInner";
s_shadow_spread_positive.name = "ShadowSpreadPositive";
s_shadow_spread_negative.name = "ShadowSpreadNegative";
s_shadow_fill_gradient.name = "ShadowFillGradient";
s_shadow_layered.name = "ShadowLayered";
s_effect_blur.name = "EffectBlur";
s_effect_blur_backdrop.name = "EffectBlurBackdrop";
s_effect_directional_blur.name = "EffectDirectionalBlur";
s_effect_directional_blur_backdrop.name = "EffectDirectionalBlurBackdrop";
s_effect_grayscale.name = "EffectGrayscale";
s_effect_grayscale_backdrop.name = "EffectGrayscaleBackdrop";
s_effect_pixelate.name = "EffectPixelate";
s_effect_pixelate_sharp.name = "EffectPixelateSharp";
s_effect_pixelate_backdrop.name = "EffectPixelateBackdrop";
s_effect_bulge_barrel.name = "EffectBulgeBarrel";
s_effect_bulge_pincushion.name = "EffectBulgePincushion";
s_effect_magnify.name = "EffectMagnify";
s_effect_bloom.name = "EffectBloom";
s_effect_vintage.name = "EffectVintage";
s_effect_chromatic_aberration.name = "EffectChromaticAberration";
s_effect_invert.name = "EffectInvert";
s_effect_scatter_horizontal.name = "EffectScatterHorizontal";
s_effect_scatter_vertical.name = "EffectScatterVertical";
s_effect_scatter_both.name = "EffectScatterBoth";
s_effect_posterize.name = "EffectPosterize";
s_effect_outline.name = "EffectOutline";
s_effect_outline_inside.name = "EffectOutlineInside";
s_effect_vignette.name = "EffectVignette";
s_effect_grain.name = "EffectGrain";
s_effect_sharpen.name = "EffectSharpen";
s_effect_edges.name = "EffectEdges";
s_effect_threshold.name = "EffectThreshold";
s_effect_radial_blur.name = "EffectRadialBlur";
s_effect_radial_blur_spin.name = "EffectRadialBlurSpin";
s_effect_halftone.name = "EffectHalftone";
s_effect_dither.name = "EffectDither";
s_effect_duotone.name = "EffectDuotone";
s_effect_curves.name = "EffectCurves";
s_effect_color_adjustment.name = "EffectColorAdjustment";
s_effect_rgb_shift.name = "EffectRgbShift";
s_effect_scanlines.name = "EffectScanlines";
s_effect_block_displace.name = "EffectBlockDisplace";
s_effect_bit_crush.name = "EffectBitCrush";
s_effect_streak.name = "EffectStreak";
s_effect_god_rays.name = "EffectGodRays";
s_effect_oil_paint.name = "EffectOilPaint";
s_effect_texture.name = "EffectTexture";
s_effect_ascii.name = "EffectAscii";
s_effect_chain_order.name = "EffectChainOrder";
s_effect_sksl_custom.name = "EffectSkslCustom";
s_effect_sksl_backdrop.name = "EffectSkslBackdrop";
s_filter_exposure.name = "FilterExposure";
s_filter_blur_image.name = "FilterBlurImage";
s_filter_grayscale_image.name = "FilterGrayscaleImage";
s_filter_alpha_image.name = "FilterAlphaImage";
s_filter_color_matrix.name = "FilterColorMatrix";
s_filter_curves.name = "FilterCurves";
s_filter_curves_per_channel.name = "FilterCurvesPerChannel";
s_filter_color_adjustment.name = "FilterColorAdjustment";
s_filter_video_exposure.name = "FilterVideoExposure";
s_filter_video_grayscale.name = "FilterVideoGrayscale";
s_filter_video_color_adjustment.name = "FilterVideoColorAdjustment";
s_filter_video_posterize_time.name = "FilterVideoPosterizeTime";
s_filter_video_echo.name = "FilterVideoEcho";
s_blend_node_multiply.name = "BlendNodeMultiply";
s_blend_node_screen.name = "BlendNodeScreen";
s_blend_node_overlay.name = "BlendNodeOverlay";
s_blend_node_darken.name = "BlendNodeDarken";
s_blend_node_lighten.name = "BlendNodeLighten";
s_blend_node_color_dodge.name = "BlendNodeColorDodge";
s_blend_node_color_burn.name = "BlendNodeColorBurn";
s_blend_node_hard_light.name = "BlendNodeHardLight";
s_blend_node_soft_light.name = "BlendNodeSoftLight";
s_blend_node_difference.name = "BlendNodeDifference";
s_blend_node_exclusion.name = "BlendNodeExclusion";
s_blend_node_hue.name = "BlendNodeHue";
s_blend_node_saturation.name = "BlendNodeSaturation";
s_blend_node_color.name = "BlendNodeColor";
s_blend_node_luminosity.name = "BlendNodeLuminosity";
s_blend_node_pass_through.name = "BlendNodePassThrough";
s_blend_fill_multiply.name = "BlendFillMultiply";
s_blend_fill_screen.name = "BlendFillScreen";
s_blend_fill_overlay.name = "BlendFillOverlay";
s_blend_fill_difference.name = "BlendFillDifference";
s_blend_fill_color_dodge.name = "BlendFillColorDodge";
s_blend_fill_luminosity.name = "BlendFillLuminosity";
s_blend_fill_layered_stack.name = "BlendFillLayeredStack";
s_blend_stroke_screen.name = "BlendStrokeScreen";
s_blend_stroke_multiply.name = "BlendStrokeMultiply";
s_blend_stroke_difference.name = "BlendStrokeDifference";
s_blend_shadow_screen.name = "BlendShadowScreen";
s_blend_shadow_multiply.name = "BlendShadowMultiply";
s_blend_shadow_color_dodge.name = "BlendShadowColorDodge";
s_transform_position.name = "TransformPosition";
s_transform_rotation.name = "TransformRotation";
s_transform_scale_uniform.name = "TransformScaleUniform";
s_transform_scale_xy.name = "TransformScaleXy";
s_transform_opacity.name = "TransformOpacity";
s_transform_pivot_center.name = "TransformPivotCenter";
s_transform_pivot_corner.name = "TransformPivotCorner";
s_transform_pivot_custom.name = "TransformPivotCustom";
s_transform_combined.name = "TransformCombined";
s_ease_sine.name = "EaseSine";
s_ease_quad.name = "EaseQuad";
s_ease_cubic.name = "EaseCubic";
s_ease_quart.name = "EaseQuart";
s_ease_quint.name = "EaseQuint";
s_ease_expo.name = "EaseExpo";
s_ease_circ.name = "EaseCirc";
s_ease_back.name = "EaseBack";
s_ease_elastic.name = "EaseElastic";
s_ease_bounce.name = "EaseBounce";
s_cardinal_node_topleft.name = "CardinalNodeTopleft";
s_cardinal_node_topcenter.name = "CardinalNodeTopcenter";
s_cardinal_node_topright.name = "CardinalNodeTopright";
s_cardinal_node_leftcenter.name = "CardinalNodeLeftcenter";
s_cardinal_node_center.name = "CardinalNodeCenter";
s_cardinal_node_rightcenter.name = "CardinalNodeRightcenter";
s_cardinal_node_bottomleft.name = "CardinalNodeBottomleft";
s_cardinal_node_bottomcenter.name = "CardinalNodeBottomcenter";
s_cardinal_node_bottomright.name = "CardinalNodeBottomright";
s_cardinal_graphics_points.name = "CardinalGraphicsPoints";
s_cardinal_graphics_rect.name = "CardinalGraphicsRect";
s_cardinal_graphics_text.name = "CardinalGraphicsText";
s_cardinal_graphics_ellipse.name = "CardinalGraphicsEllipse";
s_cardinal_graphics_polygon.name = "CardinalGraphicsPolygon";
s_cardinal_graphics_polygram.name = "CardinalGraphicsPolygram";
s_shape_start_end_rect.name = "ShapeStartEndRect";
s_shape_start_end_ellipse.name = "ShapeStartEndEllipse";
s_shape_start_end_polygon.name = "ShapeStartEndPolygon";
s_shape_start_end_line.name = "ShapeStartEndLine";
s_morph_triangle_to_star.name = "MorphTriangleToStar";
s_morph_circle_to_rect.name = "MorphCircleToRect";
s_morph_complex_shapes.name = "MorphComplexShapes";
s_opacity_node.name = "OpacityNode";
s_opacity_fill.name = "OpacityFill";
s_opacity_stroke.name = "OpacityStroke";
s_opacity_passthrough_vs_normal.name = "OpacityPassthroughVsNormal";
s_preset_vhs.name = "PresetVhs";
s_preset_comic.name = "PresetComic";
s_view3d_basic.name = "View3dBasic";
s_view3d_fill_shape.name = "View3dFillShape";
s_view3d_tex_surface.name = "View3dTexSurface";
s_view3d_translucent.name = "View3dTranslucent";

/** Every e2e scene instance, in TESTS.md order. Feeds createProject({ scenes }). */
export const scenes: Scene[] = [
    s_rect_basic,
    s_rect_corner_radius,
    s_rect_corner_radius_per_corner,
    s_rect_corner_style_angled,
    s_ellipse_circle,
    s_ellipse_arc,
    s_ellipse_pie,
    s_ellipse_ratio,
    s_polygon_triangle,
    s_polygon_pentagon,
    s_polygon_hexagon,
    s_polygon_corner_radius,
    s_polygon_corner_angled,
    s_polygram_star_5,
    s_polygram_star_6,
    s_polygram_star_ratio,
    s_polygram_rounded,
    s_path_svg_string,
    s_path_morph,
    s_line_open,
    s_line_closed,
    s_line_rounded,
    s_rect_layout_row,
    s_rect_layout_column,
    s_rect_layout_stack,
    s_rect_layout_gap,
    s_rect_layout_padding,
    s_rect_layout_padding_per_side,
    s_rect_size_fill,
    s_rect_size_hug,
    s_rect_size_max_constraints,
    s_flex_align,
    s_flex_main_flex,
    s_grid_basic,
    s_grid_colspan,
    s_text_basic,
    s_text_multiline_wrap,
    s_text_align_variants,
    s_text_font_weight,
    s_text_letter_spacing,
    s_text_line_height,
    s_text_autofit,
    s_text_on_path,
    s_text_fill_gradient,
    s_richtext_basic,
    s_richtext_inline_stroke,
    s_number_node_integer,
    s_number_node_currency,
    s_number_node_percent,
    s_image_fit_fill,
    s_image_fit_fit,
    s_image_fit_tile,
    s_image_fit_stretch,
    s_image_crop,
    s_image_zoom_anchor,
    s_video_playback,
    s_video_speed,
    s_video_loop,
    s_camera_zoom,
    s_camera_pan,
    s_camera_heading,
    s_camera_combined,
    s_mask_alpha,
    s_mask_vector,
    s_mask_luminance,
    s_mask_invert,
    s_mask_apply_fill,
    s_mask_apply_stroke,
    s_boolean_toggle,
    s_provider_theme,
    s_default_text_style,
    s_line_grid_basic,
    s_line_grid_subdivisions,
    s_grid_pattern_basic,
    s_grid_pattern_subdivisions,
    s_code_basic,
    s_code_theme_github_dark,
    s_code_theme_github_light,
    s_code_theme_vscode_dark,
    s_code_theme_vscode_light,
    s_code_line_numbers,
    s_code_padding,
    s_code_append,
    s_code_prepend,
    s_code_insert,
    s_code_remove,
    s_code_replace,
    s_code_highlight,
    s_code_highlight_reset,
    s_latex_basic,
    s_latex_complex,
    s_latex_morph,
    s_latex_fill_gradient,
    s_latex_stroke,
    s_fill_solid,
    s_fill_linear_gradient,
    s_fill_radial_gradient,
    s_fill_conic_gradient,
    s_fill_image,
    s_fill_video,
    s_fill_noise,
    s_fill_shader_custom,
    s_fill_stripe,
    s_view3d_basic,
    s_view3d_fill_shape,
    s_view3d_tex_surface,
    s_view3d_translucent,
    s_fill_space_local,
    s_fill_space_parent,
    s_fill_space_global,
    s_fill_layered,
    s_overlay_basic,
    s_overlay_video,
    s_stroke_align_inside,
    s_stroke_align_center,
    s_stroke_align_outside,
    s_stroke_cap_butt,
    s_stroke_cap_round,
    s_stroke_cap_square,
    s_stroke_join_miter,
    s_stroke_join_round,
    s_stroke_join_bevel,
    s_stroke_dash_uniform,
    s_stroke_dash_pair,
    s_stroke_dash_animated,
    s_stroke_gradient_fill,
    s_stroke_layered,
    s_stroke_miter_limit,
    s_shadow_drop_basic,
    s_shadow_drop_offset,
    s_shadow_drop_blur,
    s_shadow_inner,
    s_shadow_spread_positive,
    s_shadow_spread_negative,
    s_shadow_fill_gradient,
    s_shadow_layered,
    s_effect_blur,
    s_effect_blur_backdrop,
    s_effect_directional_blur,
    s_effect_directional_blur_backdrop,
    s_effect_grayscale,
    s_effect_grayscale_backdrop,
    s_effect_pixelate,
    s_effect_pixelate_sharp,
    s_effect_pixelate_backdrop,
    s_effect_bulge_barrel,
    s_effect_bulge_pincushion,
    s_effect_magnify,
    s_effect_bloom,
    s_effect_vintage,
    s_effect_chromatic_aberration,
    s_effect_invert,
    s_effect_scatter_horizontal,
    s_effect_scatter_vertical,
    s_effect_scatter_both,
    s_effect_posterize,
    s_effect_outline,
    s_effect_outline_inside,
    s_effect_vignette,
    s_effect_grain,
    s_effect_sharpen,
    s_effect_edges,
    s_effect_threshold,
    s_effect_radial_blur,
    s_effect_radial_blur_spin,
    s_effect_halftone,
    s_effect_dither,
    s_effect_duotone,
    s_effect_curves,
    s_effect_color_adjustment,
    s_effect_rgb_shift,
    s_effect_scanlines,
    s_effect_block_displace,
    s_effect_bit_crush,
    s_effect_streak,
    s_effect_god_rays,
    s_effect_oil_paint,
    s_effect_texture,
    s_effect_ascii,
    s_effect_chain_order,
    s_effect_sksl_custom,
    s_effect_sksl_backdrop,
    s_filter_exposure,
    s_filter_blur_image,
    s_filter_grayscale_image,
    s_filter_alpha_image,
    s_filter_color_matrix,
    s_filter_curves,
    s_filter_curves_per_channel,
    s_filter_color_adjustment,
    s_filter_video_exposure,
    s_filter_video_grayscale,
    s_filter_video_color_adjustment,
    s_filter_video_posterize_time,
    s_filter_video_echo,
    s_blend_node_multiply,
    s_blend_node_screen,
    s_blend_node_overlay,
    s_blend_node_darken,
    s_blend_node_lighten,
    s_blend_node_color_dodge,
    s_blend_node_color_burn,
    s_blend_node_hard_light,
    s_blend_node_soft_light,
    s_blend_node_difference,
    s_blend_node_exclusion,
    s_blend_node_hue,
    s_blend_node_saturation,
    s_blend_node_color,
    s_blend_node_luminosity,
    s_blend_node_pass_through,
    s_blend_fill_multiply,
    s_blend_fill_screen,
    s_blend_fill_overlay,
    s_blend_fill_difference,
    s_blend_fill_color_dodge,
    s_blend_fill_luminosity,
    s_blend_fill_layered_stack,
    s_blend_stroke_screen,
    s_blend_stroke_multiply,
    s_blend_stroke_difference,
    s_blend_shadow_screen,
    s_blend_shadow_multiply,
    s_blend_shadow_color_dodge,
    s_transform_position,
    s_transform_rotation,
    s_transform_scale_uniform,
    s_transform_scale_xy,
    s_transform_opacity,
    s_transform_pivot_center,
    s_transform_pivot_corner,
    s_transform_pivot_custom,
    s_transform_combined,
    s_ease_sine,
    s_ease_quad,
    s_ease_cubic,
    s_ease_quart,
    s_ease_quint,
    s_ease_expo,
    s_ease_circ,
    s_ease_back,
    s_ease_elastic,
    s_ease_bounce,
    s_cardinal_node_topleft,
    s_cardinal_node_topcenter,
    s_cardinal_node_topright,
    s_cardinal_node_leftcenter,
    s_cardinal_node_center,
    s_cardinal_node_rightcenter,
    s_cardinal_node_bottomleft,
    s_cardinal_node_bottomcenter,
    s_cardinal_node_bottomright,
    s_cardinal_graphics_points,
    s_cardinal_graphics_rect,
    s_cardinal_graphics_text,
    s_cardinal_graphics_ellipse,
    s_cardinal_graphics_polygon,
    s_cardinal_graphics_polygram,
    s_shape_start_end_rect,
    s_shape_start_end_ellipse,
    s_shape_start_end_polygon,
    s_shape_start_end_line,
    s_morph_triangle_to_star,
    s_morph_circle_to_rect,
    s_morph_complex_shapes,
    s_opacity_node,
    s_opacity_fill,
    s_opacity_stroke,
    s_opacity_passthrough_vs_normal,
    s_preset_vhs,
    s_preset_comic,
];

export interface SceneMeta {
    /** The TESTS.md checkbox id, e.g. "rect-basic" — also the scene filename. */
    id: string;
    /** PascalCase of the id — the name the headless bridge reports (see scene-name.ts). */
    name: string;
    /** The TESTS.md section the checkbox lives under, e.g. "Geometry". */
    section: string;
    /** The checkbox description text. */
    description: string;
}

/** Metadata for every scene, in TESTS.md order. Consumed by the screenshot harness. */
export const catalog: SceneMeta[] = [
    { id: "rect-basic", name: "RectBasic", section: "Geometry", description: "Rect with fixed width/height, solid fill" },
    { id: "rect-corner-radius", name: "RectCornerRadius", section: "Geometry", description: "Rect with uniform corner radius (rounded style)" },
    { id: "rect-corner-radius-per-corner", name: "RectCornerRadiusPerCorner", section: "Geometry", description: "Rect with 4 different corner radii" },
    { id: "rect-corner-style-angled", name: "RectCornerStyleAngled", section: "Geometry", description: "Rect with angled/chamfer corner style" },
    { id: "ellipse-circle", name: "EllipseCircle", section: "Geometry", description: "Ellipse at 1:1 ratio (circle)" },
    { id: "ellipse-arc", name: "EllipseArc", section: "Geometry", description: "Ellipse with partial sweep and startAngle" },
    { id: "ellipse-pie", name: "EllipsePie", section: "Geometry", description: "Ellipse sweep creating a pie/wedge shape" },
    { id: "ellipse-ratio", name: "EllipseRatio", section: "Geometry", description: "Ellipse with non-1 ratio (ring/donut)" },
    { id: "polygon-triangle", name: "PolygonTriangle", section: "Geometry", description: "3-sided polygon" },
    { id: "polygon-pentagon", name: "PolygonPentagon", section: "Geometry", description: "5-sided polygon" },
    { id: "polygon-hexagon", name: "PolygonHexagon", section: "Geometry", description: "6-sided polygon" },
    { id: "polygon-corner-radius", name: "PolygonCornerRadius", section: "Geometry", description: "Polygon with rounded corners" },
    { id: "polygon-corner-angled", name: "PolygonCornerAngled", section: "Geometry", description: "Polygon with angled corners" },
    { id: "polygram-star-5", name: "PolygramStar5", section: "Geometry", description: "5-point star (polygram, default ratio)" },
    { id: "polygram-star-6", name: "PolygramStar6", section: "Geometry", description: "6-point star" },
    { id: "polygram-star-ratio", name: "PolygramStarRatio", section: "Geometry", description: "Star with low ratio (sharper points)" },
    { id: "polygram-rounded", name: "PolygramRounded", section: "Geometry", description: "Star with rounded inner/outer corners" },
    { id: "path-svg-string", name: "PathSvgString", section: "Geometry", description: "Path from SVG `d` string" },
    { id: "path-morph", name: "PathMorph", section: "Geometry", description: "Animated path morph between two shapes" },
    { id: "line-open", name: "LineOpen", section: "Geometry", description: "Open multi-point line" },
    { id: "line-closed", name: "LineClosed", section: "Geometry", description: "Closed multi-point line (polygon via line)" },
    { id: "line-rounded", name: "LineRounded", section: "Geometry", description: "Line with rounded joins" },
    { id: "rect-layout-row", name: "RectLayoutRow", section: "Layout", description: "Rect in row layout mode with child rects" },
    { id: "rect-layout-column", name: "RectLayoutColumn", section: "Layout", description: "Rect in column layout mode with child rects" },
    { id: "rect-layout-stack", name: "RectLayoutStack", section: "Layout", description: "Rect in stack layout mode (overlapping children)" },
    { id: "rect-layout-gap", name: "RectLayoutGap", section: "Layout", description: "Row/column with explicit gap" },
    { id: "rect-layout-padding", name: "RectLayoutPadding", section: "Layout", description: "Rect with uniform padding around children" },
    { id: "rect-layout-padding-per-side", name: "RectLayoutPaddingPerSide", section: "Layout", description: "Rect with different padding on each side" },
    { id: "rect-size-fill", name: "RectSizeFill", section: "Layout", description: "Child using `\"fill\"` size inside parent" },
    { id: "rect-size-hug", name: "RectSizeHug", section: "Layout", description: "Parent using `\"hug\"` size around children" },
    { id: "rect-size-max-constraints", name: "RectSizeMaxConstraints", section: "Layout", description: "Child constrained by `maxWidth`/`maxHeight`" },
    { id: "flex-align", name: "FlexAlign", section: "Layout", description: "Flex container with various alignment combinations" },
    { id: "flex-main-flex", name: "FlexMainFlex", section: "Layout", description: "Children with different `mainFlex` weights distributing free space" },
    { id: "grid-basic", name: "GridBasic", section: "Layout", description: "Grid with explicit columns and uniform children" },
    { id: "grid-colspan", name: "GridColspan", section: "Layout", description: "Grid with colSpan and rowSpan variants" },
    { id: "text-basic", name: "TextBasic", section: "Text", description: "Single-line text, default style" },
    { id: "text-multiline-wrap", name: "TextMultilineWrap", section: "Text", description: "Text with wrap and constrained width" },
    { id: "text-align-variants", name: "TextAlignVariants", section: "Text", description: "Left/center/right/justify alignment in one scene" },
    { id: "text-font-weight", name: "TextFontWeight", section: "Text", description: "Multiple weights of same font family" },
    { id: "text-letter-spacing", name: "TextLetterSpacing", section: "Text", description: "Positive and negative letterSpacing" },
    { id: "text-line-height", name: "TextLineHeight", section: "Text", description: "Multiline text with custom lineHeight" },
    { id: "text-autofit", name: "TextAutofit", section: "Text", description: "Text with `\"autofit\"` size scaling to bounds" },
    { id: "text-on-path", name: "TextOnPath", section: "Text", description: "Text laid along a circular/curved SVG path" },
    { id: "text-fill-gradient", name: "TextFillGradient", section: "Text", description: "Text with a gradient fill instead of solid color" },
    { id: "richtext-basic", name: "RichtextBasic", section: "Text", description: "RichText with nested spans, each a different style" },
    { id: "richtext-inline-stroke", name: "RichtextInlineStroke", section: "Text", description: "RichText span with stroke applied to one word" },
    { id: "number-node-integer", name: "NumberNodeInteger", section: "Text", description: "NumberNode counting from 0 to 1000" },
    { id: "number-node-currency", name: "NumberNodeCurrency", section: "Text", description: "NumberNode formatted as currency" },
    { id: "number-node-percent", name: "NumberNodePercent", section: "Text", description: "NumberNode formatted as percentage" },
    { id: "image-fit-fill", name: "ImageFitFill", section: "Media", description: "Image with `fill` fit mode" },
    { id: "image-fit-fit", name: "ImageFitFit", section: "Media", description: "Image with `fit` fit mode" },
    { id: "image-fit-tile", name: "ImageFitTile", section: "Media", description: "Image with `tile` fit mode" },
    { id: "image-fit-stretch", name: "ImageFitStretch", section: "Media", description: "Image with `stretch` fit mode" },
    { id: "image-crop", name: "ImageCrop", section: "Media", description: "Image `crop` window opening from a tight centre crop to the full frame" },
    { id: "image-zoom-anchor", name: "ImageZoomAnchor", section: "Media", description: "Image `zoom` push anchored at the top-left corner" },
    { id: "video-playback", name: "VideoPlayback", section: "Media", description: "Video node playing, with trim start/end" },
    { id: "video-speed", name: "VideoSpeed", section: "Media", description: "Video node at 2\u00d7 speed" },
    { id: "video-loop", name: "VideoLoop", section: "Media", description: "Video node looping over a short clip" },
    { id: "camera-zoom", name: "CameraZoom", section: "Camera", description: "Camera zooming in on a scene" },
    { id: "camera-pan", name: "CameraPan", section: "Camera", description: "Camera panning (origin offset) across objects" },
    { id: "camera-heading", name: "CameraHeading", section: "Camera", description: "Camera rotating (heading) around viewport center" },
    { id: "camera-combined", name: "CameraCombined", section: "Camera", description: "Zoom + pan + heading all animated together" },
    { id: "mask-alpha", name: "MaskAlpha", section: "Control Nodes", description: "Mask in alpha mode (soft edge via gradient)" },
    { id: "mask-vector", name: "MaskVector", section: "Control Nodes", description: "Mask in vector mode (hard geometric clip)" },
    { id: "mask-luminance", name: "MaskLuminance", section: "Control Nodes", description: "Mask in luminance mode (grayscale as transparency)" },
    { id: "mask-invert", name: "MaskInvert", section: "Control Nodes", description: "Inverted mask (shows where mask is NOT)" },
    { id: "mask-apply-fill", name: "MaskApplyFill", section: "Control Nodes", description: "Mask with `apply: \"fill\"` (only fill layer is masked, stroke shows through)" },
    { id: "mask-apply-stroke", name: "MaskApplyStroke", section: "Control Nodes", description: "Mask with `apply: \"stroke\"` (only stroke layer is masked)" },
    { id: "boolean-toggle", name: "BooleanToggle", section: "Control Nodes", description: "Boolean node toggling child visibility at midpoint" },
    { id: "provider-theme", name: "ProviderTheme", section: "Control Nodes", description: "Provider + ThemeProvider supplying custom theme colors" },
    { id: "default-text-style", name: "DefaultTextStyle", section: "Control Nodes", description: "DefaultTextStyle node overriding font family for subtree" },
    { id: "line-grid-basic", name: "LineGridBasic", section: "Grid / Pattern", description: "LineGrid with major divisions only" },
    { id: "line-grid-subdivisions", name: "LineGridSubdivisions", section: "Grid / Pattern", description: "LineGrid with major and minor subdivisions" },
    { id: "grid-pattern-basic", name: "GridPatternBasic", section: "Grid / Pattern", description: "GridPattern (infinite world-space) with default cell size" },
    { id: "grid-pattern-subdivisions", name: "GridPatternSubdivisions", section: "Grid / Pattern", description: "GridPattern with sub-grid lines" },
    { id: "code-basic", name: "CodeBasic", section: "Component Nodes", description: "Code node with TypeScript snippet, default theme" },
    { id: "code-theme-github-dark", name: "CodeThemeGithubDark", section: "Component Nodes", description: "Code node with `github-dark` theme" },
    { id: "code-theme-github-light", name: "CodeThemeGithubLight", section: "Component Nodes", description: "Code node with `github-light` theme" },
    { id: "code-theme-vscode-dark", name: "CodeThemeVscodeDark", section: "Component Nodes", description: "Code node with `vscode-dark` theme" },
    { id: "code-theme-vscode-light", name: "CodeThemeVscodeLight", section: "Component Nodes", description: "Code node with `vscode-light` theme" },
    { id: "code-line-numbers", name: "CodeLineNumbers", section: "Component Nodes", description: "Code node with `showLineNumbers: true`" },
    { id: "code-padding", name: "CodePadding", section: "Component Nodes", description: "Code node with explicit padding on all sides" },
    { id: "code-append", name: "CodeAppend", section: "Component Nodes", description: "Code node using `append()` to add lines with animated height reveal" },
    { id: "code-prepend", name: "CodePrepend", section: "Component Nodes", description: "Code node using `prepend()` to insert lines at top" },
    { id: "code-insert", name: "CodeInsert", section: "Component Nodes", description: "Code node using `insert()` at a specific line/column" },
    { id: "code-remove", name: "CodeRemove", section: "Component Nodes", description: "Code node using `remove()` on a range of lines" },
    { id: "code-replace", name: "CodeReplace", section: "Component Nodes", description: "Code node using `replace()` swapping one token for another" },
    { id: "code-highlight", name: "CodeHighlight", section: "Component Nodes", description: "Code node using `highlight()` to dim non-highlighted tokens" },
    { id: "code-highlight-reset", name: "CodeHighlightReset", section: "Component Nodes", description: "Code node calling `resetHighlight()` to un-dim all tokens" },
    { id: "latex-basic", name: "LatexBasic", section: "Component Nodes", description: "Latex node rendering a simple formula (e.g. `E = mc^2`)" },
    { id: "latex-complex", name: "LatexComplex", section: "Component Nodes", description: "Latex node rendering a complex expression (fraction, sum, integral)" },
    { id: "latex-morph", name: "LatexMorph", section: "Component Nodes", description: "Latex node morphing between two formulas via `to()`" },
    { id: "latex-fill-gradient", name: "LatexFillGradient", section: "Component Nodes", description: "Latex node with a gradient fill applied to glyphs" },
    { id: "latex-stroke", name: "LatexStroke", section: "Component Nodes", description: "Latex node with stroke outline on glyphs" },
    { id: "fill-solid", name: "FillSolid", section: "Fills", description: "Solid color fill (static and animated color)" },
    { id: "fill-linear-gradient", name: "FillLinearGradient", section: "Fills", description: "Linear gradient, horizontal then animated angle" },
    { id: "fill-radial-gradient", name: "FillRadialGradient", section: "Fills", description: "Radial gradient centered on shape" },
    { id: "fill-conic-gradient", name: "FillConicGradient", section: "Fills", description: "Conic gradient full sweep" },
    { id: "fill-image", name: "FillImage", section: "Fills", description: "Image fill on a rect" },
    { id: "fill-video", name: "FillVideo", section: "Fills", description: "Video fill on a rect" },
    { id: "fill-noise", name: "FillNoise", section: "Fills", description: "Noise fill, varying density and size" },
    { id: "fill-shader-custom", name: "FillShaderCustom", section: "Fills", description: "Custom SkSL shader fill, ring radius driven by a tweened uniform" },
    { id: "fill-stripe", name: "FillStripe", section: "Fills", description: "Stripe fill, varying angle and gap" },
    { id: "fill-space-local", name: "FillSpaceLocal", section: "Fills", description: "Fill pinned to shape's own bounds (default)" },
    { id: "fill-space-parent", name: "FillSpaceParent", section: "Fills", description: "Fill mapped to parent bounds; shape moves across it" },
    { id: "fill-space-global", name: "FillSpaceGlobal", section: "Fills", description: "Fill anchored to viewport; node moves over it" },
    { id: "fill-layered", name: "FillLayered", section: "Fills", description: "Multiple fill layers stacked on one shape (solid + gradient + noise)" },
    { id: "overlay-basic", name: "OverlayBasic", section: "Fills", description: "Overlay fill painted over children but under stroke (grain texture over a rect with child rects)" },
    { id: "overlay-video", name: "OverlayVideo", section: "Fills", description: "Video overlay across an entire subtree" },
    { id: "stroke-align-inside", name: "StrokeAlignInside", section: "Strokes", description: "Stroke aligned inside shape boundary" },
    { id: "stroke-align-center", name: "StrokeAlignCenter", section: "Strokes", description: "Stroke centered on shape boundary" },
    { id: "stroke-align-outside", name: "StrokeAlignOutside", section: "Strokes", description: "Stroke aligned outside shape boundary" },
    { id: "stroke-cap-butt", name: "StrokeCapButt", section: "Strokes", description: "Line ends with butt cap" },
    { id: "stroke-cap-round", name: "StrokeCapRound", section: "Strokes", description: "Line ends with round cap" },
    { id: "stroke-cap-square", name: "StrokeCapSquare", section: "Strokes", description: "Line ends with square cap" },
    { id: "stroke-join-miter", name: "StrokeJoinMiter", section: "Strokes", description: "Corner joins with miter style" },
    { id: "stroke-join-round", name: "StrokeJoinRound", section: "Strokes", description: "Corner joins with round style" },
    { id: "stroke-join-bevel", name: "StrokeJoinBevel", section: "Strokes", description: "Corner joins with bevel style" },
    { id: "stroke-dash-uniform", name: "StrokeDashUniform", section: "Strokes", description: "Stroke with uniform dash pattern" },
    { id: "stroke-dash-pair", name: "StrokeDashPair", section: "Strokes", description: "Stroke with `[on, off]` dash pair" },
    { id: "stroke-dash-animated", name: "StrokeDashAnimated", section: "Strokes", description: "Animated dashOffset (marching ants)" },
    { id: "stroke-gradient-fill", name: "StrokeGradientFill", section: "Strokes", description: "Stroke using a linear gradient fill" },
    { id: "stroke-layered", name: "StrokeLayered", section: "Strokes", description: "Multiple strokes stacked on one shape" },
    { id: "stroke-miter-limit", name: "StrokeMiterLimit", section: "Strokes", description: "High miterLimit vs low miterLimit on a sharp-angle polygon" },
    { id: "shadow-drop-basic", name: "ShadowDropBasic", section: "Shadows", description: "Basic drop shadow (blur + offset)" },
    { id: "shadow-drop-offset", name: "ShadowDropOffset", section: "Shadows", description: "Shadow with large x/y offset" },
    { id: "shadow-drop-blur", name: "ShadowDropBlur", section: "Shadows", description: "Shadow with high blur, zero offset (glow-like)" },
    { id: "shadow-inner", name: "ShadowInner", section: "Shadows", description: "Inner shadow on rect" },
    { id: "shadow-spread-positive", name: "ShadowSpreadPositive", section: "Shadows", description: "Shadow with positive spread (expanded)" },
    { id: "shadow-spread-negative", name: "ShadowSpreadNegative", section: "Shadows", description: "Shadow with negative spread (contracted)" },
    { id: "shadow-fill-gradient", name: "ShadowFillGradient", section: "Shadows", description: "Shadow using a gradient fill color" },
    { id: "shadow-layered", name: "ShadowLayered", section: "Shadows", description: "Multiple shadows stacked (inner + outer)" },
    { id: "effect-blur", name: "EffectBlur", section: "Effects", description: "Gaussian blur on a rect" },
    { id: "effect-blur-backdrop", name: "EffectBlurBackdrop", section: "Effects", description: "Gaussian blur reading backdrop (frosted glass)" },
    { id: "effect-directional-blur", name: "EffectDirectionalBlur", section: "Effects", description: "Motion blur along 45\u00b0 axis" },
    { id: "effect-directional-blur-backdrop", name: "EffectDirectionalBlurBackdrop", section: "Effects", description: "Directional blur on backdrop" },
    { id: "effect-grayscale", name: "EffectGrayscale", section: "Effects", description: "Full desaturation of shape" },
    { id: "effect-grayscale-backdrop", name: "EffectGrayscaleBackdrop", section: "Effects", description: "Desaturate backdrop content beneath shape" },
    { id: "effect-pixelate", name: "EffectPixelate", section: "Effects", description: "Mosaic pixelation on a shape (`sharpColors: false`, smooth blocks)" },
    { id: "effect-pixelate-sharp", name: "EffectPixelateSharp", section: "Effects", description: "Pixelate with `sharpColors: true` (solid-color blocks)" },
    { id: "effect-pixelate-backdrop", name: "EffectPixelateBackdrop", section: "Effects", description: "Pixelate backdrop (censoring effect)" },
    { id: "effect-bulge-barrel", name: "EffectBulgeBarrel", section: "Effects", description: "Barrel distortion (positive strength)" },
    { id: "effect-bulge-pincushion", name: "EffectBulgePincushion", section: "Effects", description: "Pincushion distortion (negative strength)" },
    { id: "effect-magnify", name: "EffectMagnify", section: "Effects", description: "Magnify a portion of backdrop" },
    { id: "effect-bloom", name: "EffectBloom", section: "Effects", description: "Bloom/glow from bright regions" },
    { id: "effect-vintage", name: "EffectVintage", section: "Effects", description: "Sepia + warmth tone" },
    { id: "effect-chromatic-aberration", name: "EffectChromaticAberration", section: "Effects", description: "RGB channel fringing" },
    { id: "effect-invert", name: "EffectInvert", section: "Effects", description: "RGB inversion" },
    { id: "effect-scatter-horizontal", name: "EffectScatterHorizontal", section: "Effects", description: "Scatter with `direction: \"horizontal\"`" },
    { id: "effect-scatter-vertical", name: "EffectScatterVertical", section: "Effects", description: "Scatter with `direction: \"vertical\"`" },
    { id: "effect-scatter-both", name: "EffectScatterBoth", section: "Effects", description: "Scatter with `direction: \"both\"`" },
    { id: "effect-posterize", name: "EffectPosterize", section: "Effects", description: "Color banding at low level count" },
    { id: "effect-outline", name: "EffectOutline", section: "Effects", description: "Outline band growing outside a text silhouette" },
    { id: "effect-outline-inside", name: "EffectOutlineInside", section: "Effects", description: "Outline with `position: \"inside\"` on a filled disc" },
    { id: "effect-vignette", name: "EffectVignette", section: "Effects", description: "Corner falloff darkening a bright card" },
    { id: "effect-grain", name: "EffectGrain", section: "Effects", description: "Static (unanimated) film grain over a gradient" },
    { id: "effect-sharpen", name: "EffectSharpen", section: "Effects", description: "Unsharp mask raising edge contrast" },
    { id: "effect-edges", name: "EffectEdges", section: "Effects", description: "Sobel edge detection on flat colour blocks" },
    { id: "effect-threshold", name: "EffectThreshold", section: "Effects", description: "Two-tone luminance cut sweeping across a gradient" },
    { id: "effect-radial-blur", name: "EffectRadialBlur", section: "Effects", description: "Zoom-style radial blur about the centre" },
    { id: "effect-radial-blur-spin", name: "EffectRadialBlurSpin", section: "Effects", description: "Spin-style radial blur about the centre" },
    { id: "effect-halftone", name: "EffectHalftone", section: "Effects", description: "45\u00b0 dot screen at increasing cell size" },
    { id: "effect-dither", name: "EffectDither", section: "Effects", description: "Bayer 8\u00d78 ordered dither down to 1-bit" },
    { id: "effect-duotone", name: "EffectDuotone", section: "Effects", description: "Luminance remapped onto a two-colour ramp" },
    { id: "effect-curves", name: "EffectCurves", section: "Effects", description: "Tone curve lifting shadows on a node (not an image fill)" },
    { id: "effect-color-adjustment", name: "EffectColorAdjustment", section: "Effects", description: "Contrast/saturation/temperature on a group of shapes" },
    { id: "effect-rgb-shift", name: "EffectRgbShift", section: "Effects", description: "Red/blue planes pulled apart on a text silhouette" },
    { id: "effect-scanlines", name: "EffectScanlines", section: "Effects", description: "CRT bands darkening a bright card" },
    { id: "effect-block-displace", name: "EffectBlockDisplace", section: "Effects", description: "Horizontal band tearing at a fixed seed" },
    { id: "effect-bit-crush", name: "EffectBitCrush", section: "Effects", description: "Gradient snapped to the Game Boy palette" },
    { id: "effect-streak", name: "EffectStreak", section: "Effects", description: "Anamorphic glare smeared along one axis" },
    { id: "effect-god-rays", name: "EffectGodRays", section: "Effects", description: "Light streaming from a disc past an occluding bar" },
    { id: "effect-oil-paint", name: "EffectOilPaint", section: "Effects", description: "Kuwahara brushwork \u2014 flat strokes with edges intact" },
    { id: "effect-texture", name: "EffectTexture", section: "Effects", description: "An image multiplied over the content" },
    { id: "effect-ascii", name: "EffectAscii", section: "Effects", description: "Image resolving into an ASCII glyph grid as the cell grows" },
    { id: "effect-chain-order", name: "EffectChainOrder", section: "Effects", description: "Two shader effects in opposite orders must differ (author-order guard)" },
    { id: "effect-sksl-custom", name: "EffectSkslCustom", section: "Effects", description: "Custom SkSL shader as layer effect" },
    { id: "effect-sksl-backdrop", name: "EffectSkslBackdrop", section: "Effects", description: "Custom SkSL shader processing backdrop" },
    { id: "filter-exposure", name: "FilterExposure", section: "Image Filters", description: "Exposure boost and reduction" },
    { id: "filter-blur-image", name: "FilterBlurImage", section: "Image Filters", description: "Gaussian blur on an image" },
    { id: "filter-grayscale-image", name: "FilterGrayscaleImage", section: "Image Filters", description: "Desaturation of an image" },
    { id: "filter-alpha-image", name: "FilterAlphaImage", section: "Image Filters", description: "Alpha multiplier fading an image out" },
    { id: "filter-color-matrix", name: "FilterColorMatrix", section: "Image Filters", description: "Arbitrary 4\u00d75 color matrix transform" },
    { id: "filter-curves", name: "FilterCurves", section: "Image Filters", description: "Tone curve on RGB channel" },
    { id: "filter-curves-per-channel", name: "FilterCurvesPerChannel", section: "Image Filters", description: "Separate tone curves for R, G, B" },
    { id: "filter-color-adjustment", name: "FilterColorAdjustment", section: "Image Filters", description: "Brightness, contrast, saturation, vibrance, shadows, highlights, temperature, tint, vignette all animated" },
    { id: "filter-video-exposure", name: "FilterVideoExposure", section: "Video Filters", description: "Exposure on video" },
    { id: "filter-video-grayscale", name: "FilterVideoGrayscale", section: "Video Filters", description: "Grayscale on video" },
    { id: "filter-video-color-adjustment", name: "FilterVideoColorAdjustment", section: "Video Filters", description: "Color adjustment on video" },
    { id: "filter-video-posterize-time", name: "FilterVideoPosterizeTime", section: "Video Filters", description: "Frame rate reduction (posterize time)" },
    { id: "filter-video-echo", name: "FilterVideoEcho", section: "Video Filters", description: "Multi-frame echo/trail effect" },
    { id: "blend-node-multiply", name: "BlendNodeMultiply", section: "Node Blend Modes", description: "" },
    { id: "blend-node-screen", name: "BlendNodeScreen", section: "Node Blend Modes", description: "" },
    { id: "blend-node-overlay", name: "BlendNodeOverlay", section: "Node Blend Modes", description: "" },
    { id: "blend-node-darken", name: "BlendNodeDarken", section: "Node Blend Modes", description: "" },
    { id: "blend-node-lighten", name: "BlendNodeLighten", section: "Node Blend Modes", description: "" },
    { id: "blend-node-color-dodge", name: "BlendNodeColorDodge", section: "Node Blend Modes", description: "" },
    { id: "blend-node-color-burn", name: "BlendNodeColorBurn", section: "Node Blend Modes", description: "" },
    { id: "blend-node-hard-light", name: "BlendNodeHardLight", section: "Node Blend Modes", description: "" },
    { id: "blend-node-soft-light", name: "BlendNodeSoftLight", section: "Node Blend Modes", description: "" },
    { id: "blend-node-difference", name: "BlendNodeDifference", section: "Node Blend Modes", description: "" },
    { id: "blend-node-exclusion", name: "BlendNodeExclusion", section: "Node Blend Modes", description: "" },
    { id: "blend-node-hue", name: "BlendNodeHue", section: "Node Blend Modes", description: "" },
    { id: "blend-node-saturation", name: "BlendNodeSaturation", section: "Node Blend Modes", description: "" },
    { id: "blend-node-color", name: "BlendNodeColor", section: "Node Blend Modes", description: "" },
    { id: "blend-node-luminosity", name: "BlendNodeLuminosity", section: "Node Blend Modes", description: "" },
    { id: "blend-node-pass-through", name: "BlendNodePassThrough", section: "Node Blend Modes", description: "`\"pass-through\"` vs `\"normal\"` isolation with semi-transparent children" },
    { id: "blend-fill-multiply", name: "BlendFillMultiply", section: "Fill Blend Modes", description: "Second fill layer blending with `\"multiply\"` over first" },
    { id: "blend-fill-screen", name: "BlendFillScreen", section: "Fill Blend Modes", description: "Screen blend between two fill layers" },
    { id: "blend-fill-overlay", name: "BlendFillOverlay", section: "Fill Blend Modes", description: "Overlay blend between two fill layers" },
    { id: "blend-fill-difference", name: "BlendFillDifference", section: "Fill Blend Modes", description: "Difference blend to invert where fills overlap" },
    { id: "blend-fill-color-dodge", name: "BlendFillColorDodge", section: "Fill Blend Modes", description: "Color-dodge brightening effect between fill layers" },
    { id: "blend-fill-luminosity", name: "BlendFillLuminosity", section: "Fill Blend Modes", description: "Luminosity blend preserving luma from top fill" },
    { id: "blend-fill-layered-stack", name: "BlendFillLayeredStack", section: "Fill Blend Modes", description: "Three fill layers each with different blend modes stacked" },
    { id: "blend-stroke-screen", name: "BlendStrokeScreen", section: "Stroke Blend Modes", description: "Stroke fill using `\"screen\"` blend over the shape fill" },
    { id: "blend-stroke-multiply", name: "BlendStrokeMultiply", section: "Stroke Blend Modes", description: "Stroke fill using `\"multiply\"` blend" },
    { id: "blend-stroke-difference", name: "BlendStrokeDifference", section: "Stroke Blend Modes", description: "Stroke fill using `\"difference\"` blend (inverts where stroke crosses fill)" },
    { id: "blend-shadow-screen", name: "BlendShadowScreen", section: "Shadow Blend Modes", description: "Drop shadow using `\"screen\"` blend (lightening glow)" },
    { id: "blend-shadow-multiply", name: "BlendShadowMultiply", section: "Shadow Blend Modes", description: "Drop shadow using `\"multiply\"` blend (darkening shadow)" },
    { id: "blend-shadow-color-dodge", name: "BlendShadowColorDodge", section: "Shadow Blend Modes", description: "Drop shadow using `\"color-dodge\"` (bloom-like outer glow)" },
    { id: "transform-position", name: "TransformPosition", section: "Transforms", description: "Rect animating x, y position" },
    { id: "transform-rotation", name: "TransformRotation", section: "Transforms", description: "Shape spinning full rotation" },
    { id: "transform-scale-uniform", name: "TransformScaleUniform", section: "Transforms", description: "Uniform scale animation" },
    { id: "transform-scale-xy", name: "TransformScaleXy", section: "Transforms", description: "Independent scaleX and scaleY (squash and stretch)" },
    { id: "transform-opacity", name: "TransformOpacity", section: "Transforms", description: "Opacity fade in/out" },
    { id: "transform-pivot-center", name: "TransformPivotCenter", section: "Transforms", description: "Rotation around center pivot" },
    { id: "transform-pivot-corner", name: "TransformPivotCorner", section: "Transforms", description: "Rotation around top-left corner pivot" },
    { id: "transform-pivot-custom", name: "TransformPivotCustom", section: "Transforms", description: "Rotation around arbitrary custom pivot point" },
    { id: "transform-combined", name: "TransformCombined", section: "Transforms", description: "Position + rotation + scale all animated simultaneously" },
    { id: "ease-sine", name: "EaseSine", section: "Easing Functions", description: "" },
    { id: "ease-quad", name: "EaseQuad", section: "Easing Functions", description: "" },
    { id: "ease-cubic", name: "EaseCubic", section: "Easing Functions", description: "" },
    { id: "ease-quart", name: "EaseQuart", section: "Easing Functions", description: "" },
    { id: "ease-quint", name: "EaseQuint", section: "Easing Functions", description: "" },
    { id: "ease-expo", name: "EaseExpo", section: "Easing Functions", description: "" },
    { id: "ease-circ", name: "EaseCirc", section: "Easing Functions", description: "" },
    { id: "ease-back", name: "EaseBack", section: "Easing Functions", description: "" },
    { id: "ease-elastic", name: "EaseElastic", section: "Easing Functions", description: "" },
    { id: "ease-bounce", name: "EaseBounce", section: "Easing Functions", description: "" },
    { id: "cardinal-node-topleft", name: "CardinalNodeTopleft", section: "Cardinal Coordinates", description: "Anchoring/measuring from topLeft of a node" },
    { id: "cardinal-node-topcenter", name: "CardinalNodeTopcenter", section: "Cardinal Coordinates", description: "topCenter" },
    { id: "cardinal-node-topright", name: "CardinalNodeTopright", section: "Cardinal Coordinates", description: "topRight" },
    { id: "cardinal-node-leftcenter", name: "CardinalNodeLeftcenter", section: "Cardinal Coordinates", description: "centerLeft" },
    { id: "cardinal-node-center", name: "CardinalNodeCenter", section: "Cardinal Coordinates", description: "center" },
    { id: "cardinal-node-rightcenter", name: "CardinalNodeRightcenter", section: "Cardinal Coordinates", description: "centerRight" },
    { id: "cardinal-node-bottomleft", name: "CardinalNodeBottomleft", section: "Cardinal Coordinates", description: "bottomLeft" },
    { id: "cardinal-node-bottomcenter", name: "CardinalNodeBottomcenter", section: "Cardinal Coordinates", description: "bottomCenter" },
    { id: "cardinal-node-bottomright", name: "CardinalNodeBottomright", section: "Cardinal Coordinates", description: "bottomRight" },
    { id: "cardinal-graphics-points", name: "CardinalGraphicsPoints", section: "Cardinal Coordinates", description: "Cardinal points used in a graphics/drawable context" },
    { id: "cardinal-graphics-rect", name: "CardinalGraphicsRect", section: "Cardinal Coordinates", description: "Graphics2D().rect({ pivot, x, y }) for all nine named anchors, animating rotation/scale" },
    { id: "cardinal-graphics-text", name: "CardinalGraphicsText", section: "Cardinal Coordinates", description: "Graphics2D().text({ pivot, x, y }) for all nine named anchors, no authored box, animating rotation/scale" },
    { id: "cardinal-graphics-ellipse", name: "CardinalGraphicsEllipse", section: "Cardinal Coordinates", description: "Graphics2D().ellipse({ pivot, x, y }) for all nine named anchors, animating rotation/scale" },
    { id: "cardinal-graphics-polygon", name: "CardinalGraphicsPolygon", section: "Cardinal Coordinates", description: "Graphics2D().polygon({ pivot, x, y }) for all nine named anchors, animating rotation/scale" },
    { id: "cardinal-graphics-polygram", name: "CardinalGraphicsPolygram", section: "Cardinal Coordinates", description: "Graphics2D().polygram({ pivot, x, y }) for all nine named anchors, animating rotation/scale" },
    { id: "shape-start-end-rect", name: "ShapeStartEndRect", section: "Shape Start / End", description: "Rect animated from `start=0,end=0` to `end=1` (draws itself in)" },
    { id: "shape-start-end-ellipse", name: "ShapeStartEndEllipse", section: "Shape Start / End", description: "Ellipse revealing arc from start to end" },
    { id: "shape-start-end-polygon", name: "ShapeStartEndPolygon", section: "Shape Start / End", description: "Polygon drawing its perimeter progressively" },
    { id: "shape-start-end-line", name: "ShapeStartEndLine", section: "Shape Start / End", description: "Line animating `start` and `end` to trim both ends" },
    { id: "morph-triangle-to-star", name: "MorphTriangleToStar", section: "Path Morphing", description: "Triangle shape morphing into 5-point star" },
    { id: "morph-circle-to-rect", name: "MorphCircleToRect", section: "Path Morphing", description: "Ellipse morphing into rectangle path" },
    { id: "morph-complex-shapes", name: "MorphComplexShapes", section: "Path Morphing", description: "Two arbitrary SVG paths morphing together" },
    { id: "opacity-node", name: "OpacityNode", section: "Opacity & Visibility", description: "Node-level opacity animated" },
    { id: "opacity-fill", name: "OpacityFill", section: "Opacity & Visibility", description: "Fill-level opacity animated independently of node" },
    { id: "opacity-stroke", name: "OpacityStroke", section: "Opacity & Visibility", description: "Stroke-level opacity animated" },
    { id: "opacity-passthrough-vs-normal", name: "OpacityPassthroughVsNormal", section: "Opacity & Visibility", description: "Pass-through vs normal node blend isolation with semi-transparent children" },
    { id: "preset-vhs", name: "PresetVhs", section: "Effects", description: "a five-effect chain spanning both effect surfaces" },
    { id: "preset-comic", name: "PresetComic", section: "Effects", description: "halftone cmyk separation on a process screen" },
    { id: "view3d-basic", name: "View3dBasic", section: "3D", description: "Lit box rotating in a Canvas3D — the baseline 3D render path" },
    { id: "view3d-fill-shape", name: "View3dFillShape", section: "3D", description: "3D painted as a fill through an Ellipse path, not a rect" },
    { id: "view3d-tex-surface", name: "View3dTexSurface", section: "3D", description: "Tex.surface: 2D Graphics2D rasterized and bound to a material map" },
    { id: "view3d-translucent", name: "View3dTranslucent", section: "3D", description: "Translucent 3D composited over a 2D fill, in a colour that separates correct blending from additive" },
];
