/**
 * Scaffold the scene catalog from TESTS.md.
 *
 * Reads every `- [ ] \`id\` — description` checkbox in scripts/TESTS.md and, for
 * each one, ensures a scene file exists at src/scenes/<id>.tsx. Files that
 * already exist are left untouched, so hand-authored sample scenes are never
 * clobbered — only missing ones get a placeholder stub. It also (re)writes
 * src/scenes/catalog.ts, the single source of truth listing every scene id in
 * TESTS.md order along with its section, which both the project entry and the
 * screenshot harness consume.
 *
 * Run from the e2e package root:  pnpm gen
 *
 * The scene *name* the headless bridge sees is the PascalCase of the filename
 * (the ?scene transform derives it), so the harness derives the same PascalCase
 * from each catalog id — see scripts/lib/scene-name.ts.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { pascalCase } from './lib/scene-name.ts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(pkgRoot, '..', '..');
const testsMd = path.join(repoRoot, 'scripts', 'TESTS.md');
const scenesDir = path.join(pkgRoot, 'src', 'scenes');

type Entry = { id: string; section: string; description: string };

/** Parse TESTS.md into ordered checkbox entries, tracking the current `##`/`###` section. */
function parseTests(md: string): Entry[] {
    const entries: Entry[] = [];
    let section = 'General';
    for (const line of md.split(/\r?\n/)) {
        const heading = line.match(/^#{2,3}\s+(.*)$/);
        if (heading) {
            section = heading[1].trim();
            continue;
        }
        // - [ ] `id` — description   (description optional)
        const box = line.match(/^\s*-\s*\[[ xX]\]\s*`([^`]+)`(?:\s*[—-]\s*(.*))?\s*$/);
        if (box) {
            entries.push({
                id: box[1].trim(),
                section,
                description: (box[2] ?? '').trim(),
            });
        }
    }
    return entries;
}

const stub = (id: string) => `/** @jsxImportSource @motion-script/core/jsx */

import { createScene } from '@motion-script/core';
import { placeholder } from './_lib';

// TODO: replace this placeholder with a real scene exercising \`${id}\`.
export default createScene(placeholder('${id}'));
`;

function main(): void {
    if (!fs.existsSync(testsMd)) {
        throw new Error(`TESTS.md not found at ${testsMd}`);
    }
    const entries = parseTests(fs.readFileSync(testsMd, 'utf8'));
    if (entries.length === 0) {
        throw new Error('No checkboxes parsed from TESTS.md — did the format change?');
    }

    // Guard against duplicate ids (they would collide as filenames / scene names).
    const seen = new Set<string>();
    for (const e of entries) {
        if (seen.has(e.id)) throw new Error(`Duplicate scene id in TESTS.md: ${e.id}`);
        seen.add(e.id);
    }

    fs.mkdirSync(scenesDir, { recursive: true });

    let created = 0;
    let kept = 0;
    for (const { id } of entries) {
        const file = path.join(scenesDir, `${id}.tsx`);
        if (fs.existsSync(file)) {
            kept++;
            continue;
        }
        fs.writeFileSync(file, stub(id), 'utf8');
        created++;
    }

    // Emit the catalog: every scene imported as a ?scene instance, in TESTS.md
    // order, plus a metadata table (id → section, sceneName) the harness reads.
    const imports = entries
        .map(({ id }) => `import ${importIdent(id)} from './${id}?scene';`)
        .join('\n');
    const sceneList = entries.map(({ id }) => `    ${importIdent(id)},`).join('\n');
    const meta = entries
        .map(
            ({ id, section, description }) =>
                `    { id: ${JSON.stringify(id)}, name: ${JSON.stringify(pascalCase(id))}, ` +
                `section: ${JSON.stringify(section)}, description: ${JSON.stringify(description)} },`,
        )
        .join('\n');

    const catalog = `// AUTO-GENERATED by scripts/gen-scenes.ts — do not edit by hand.
// Run \`pnpm gen\` in this package to regenerate from scripts/TESTS.md.
/* eslint-disable */
import type { Scene } from '@motion-script/core';

${imports}

/** Every e2e scene instance, in TESTS.md order. Feeds createProject({ scenes }). */
export const scenes: Scene[] = [
${sceneList}
];

export interface SceneMeta {
    /** The TESTS.md checkbox id, e.g. "rect-basic" — also the scene filename. */
    id: string;
    /** PascalCase of the id — the name the headless bridge reports (see scene-name.ts). */
    name: string;
    /** The TESTS.md section the checkbox lives under, e.g. "Geometry". */
    section: string;
    /** The checkbox description text. */
    description: string;
}

/** Metadata for every scene, in TESTS.md order. Consumed by the screenshot harness. */
export const catalog: SceneMeta[] = [
${meta}
];
`;
    fs.writeFileSync(path.join(scenesDir, 'catalog.ts'), catalog, 'utf8');

    // Also emit a plain JSON copy of the metadata so Node scripts (the harness)
    // can read the scene list without going through Vite / the ?scene transform.
    const metaJson = entries.map(({ id, section, description }) => ({
        id,
        name: pascalCase(id),
        section,
        description,
    }));
    fs.writeFileSync(
        path.join(scenesDir, 'catalog.json'),
        JSON.stringify(metaJson, null, 2) + '\n',
        'utf8',
    );

    console.log(
        `Catalog: ${entries.length} scenes (${created} stub(s) created, ${kept} existing kept).`,
    );
}

/** A valid JS identifier for a scene import, e.g. "rect-basic" → "rect_basic". */
function importIdent(id: string): string {
    return 's_' + id.replace(/[^a-zA-Z0-9_$]/g, '_');
}

main();
