// Build-time generator for the docs search index.
//
// The site is a static export (`output: "export"`), so there is no server at
// runtime to answer search queries. This script walks the latest-version docs
// and API pages, extracts each page's title and its h2/h3 headings, and writes a
// compact JSON index to `public/search-index.json`. The client `SearchDialog`
// fetches that asset lazily and searches it entirely in the browser.
//
// Run via Node's native TypeScript stripping (Node 22.6+ / 24) plus a tiny
// resolve hook that lets the extensionless relative imports below (and inside
// the reused data-layer modules) resolve to their `.ts` files:
//   node --import ./scripts/ts-resolve.mjs lib/build-search-index.ts
// invoked from the `packages/site` directory (see the `build:search` script).
// The data-layer modules below are Node-only (they use `fs`), which is why the
// matcher in `lib/search.ts` is kept separate and dependency-light.

import fs from "fs"
import path from "path"

import { getAllDocSlugs, getDocContent, extractTocEntries } from "./docs"
import { getAllApiSlugs, getApiContent } from "./api"
import { LATEST_VERSION, isVersionSegment, versionPrefix } from "./versions"
import type { SearchEntry, SearchIndex, SearchSection } from "./search"

// A latest-version page has no leading version segment in its URL slug
// (older versions are prefixed with their version id, e.g. ["1.0.0", ...]).
function isLatestSlug(slug: string[]): boolean {
  return slug.length > 0 && !isVersionSegment(slug[0])
}

// Expand one page into its search entries: a page-level (depth 1) entry for the
// title, plus one entry per h2/h3 heading linking to that heading's anchor.
//
// `headings` is off for the API section. Typedoc's h2s are the same two dozen
// structural labels repeated across every page ("Properties" on 360 of them,
// "Returns" on 199), and its h3s are one per member — together they outnumber
// the prose docs ten to one and would bury them in the results. An API page is
// searched for by its symbol name, which is the title.
function pageEntries(
  section: SearchSection,
  baseUrl: string,
  title: string,
  content: string,
  headings = true,
): SearchEntry[] {
  const entries: SearchEntry[] = [
    { title, heading: title, url: baseUrl, section, depth: 1 },
  ]
  if (!headings) return entries
  for (const toc of extractTocEntries(content)) {
    entries.push({
      title,
      heading: toc.text,
      url: `${baseUrl}#${toc.id}`,
      section,
      depth: toc.depth,
    })
  }
  return entries
}

function buildIndex(): SearchIndex {
  const index: SearchIndex = []

  // Docs (latest version only). getAllDocSlugs returns URL slugs already; latest
  // ones are unprefixed, so the URL is simply "/docs/<slug>".
  for (const slug of getAllDocSlugs()) {
    if (!isLatestSlug(slug)) continue
    const doc = getDocContent(slug)
    if (!doc) continue
    const url = "/docs/" + slug.join("/")
    index.push(...pageEntries("docs", url, doc.meta.title, doc.content))
  }

  // API (latest version only), indexed by symbol name rather than by heading —
  // see `pageEntries`.
  //
  // The latest API tree is the typedoc output under content/api, generated by
  // `pnpm build:api` (scripts/build-api.mjs). If it isn't present yet (a fresh
  // checkout that hasn't run it), enumerating it throws — degrade to a docs-only
  // index with a warning rather than failing the whole build. `prebuild` runs
  // build:api first, so a production build always has it.
  try {
    for (const slug of getAllApiSlugs()) {
      if (!isLatestSlug(slug)) continue
      const page = getApiContent(slug)
      if (!page) continue
      const url = "/api/" + slug.join("/")
      index.push(...pageEntries("api", url, page.title, page.content, false))
    }
  } catch (err) {
    console.warn(
      "search-index: skipping API pages (typedoc tree unavailable):",
      err instanceof Error ? err.message : err,
    )
  }

  return index
}

function main() {
  // Sanity-check the working directory: the data layer resolves content paths
  // relative to process.cwd() (versionContentDir uses process.cwd()), so the
  // script must run from packages/site. versionPrefix(LATEST) is [] — a cheap
  // assertion that the versions module loaded.
  void versionPrefix(LATEST_VERSION)

  const index = buildIndex()
  const outDir = path.join(process.cwd(), "public")
  const outFile = path.join(outDir, "search-index.json")
  fs.mkdirSync(outDir, { recursive: true })
  fs.writeFileSync(outFile, JSON.stringify(index))

  const docs = index.filter((e) => e.section === "docs").length
  const api = index.filter((e) => e.section === "api").length
  const bytes = fs.statSync(outFile).size
  console.log(
    `search-index.json: ${index.length} entries (${docs} docs, ${api} api), ${(bytes / 1024).toFixed(1)} KB`,
  )
}

main()
